//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicewolf.Generator.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InvoiceMessages_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InvoiceMessages_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Invoicewolf.Generator.Localization.Resources.Messages.InvoiceMessages_en_US", typeof(InvoiceMessages_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        internal static string Regarding {
            get {
                return ResourceManager.GetString("Regarding", resourceCulture);
            }
        }
        
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        internal static string AllPricesExcludeVAT {
            get {
                return ResourceManager.GetString("AllPricesExcludeVAT", resourceCulture);
            }
        }
        
        internal static string PaymentTerm {
            get {
                return ResourceManager.GetString("PaymentTerm", resourceCulture);
            }
        }
        
        internal static string PaymentTo {
            get {
                return ResourceManager.GetString("PaymentTo", resourceCulture);
            }
        }
        
        internal static string QuestionsOrRemarks {
            get {
                return ResourceManager.GetString("QuestionsOrRemarks", resourceCulture);
            }
        }
        
        internal static string CompanyNumber {
            get {
                return ResourceManager.GetString("CompanyNumber", resourceCulture);
            }
        }
        
        internal static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        internal static string Tariff {
            get {
                return ResourceManager.GetString("Tariff", resourceCulture);
            }
        }
        
        internal static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        internal static string TaxAmount {
            get {
                return ResourceManager.GetString("TaxAmount", resourceCulture);
            }
        }
        
        internal static string TotalIncludingTax {
            get {
                return ResourceManager.GetString("TotalIncludingTax", resourceCulture);
            }
        }
    }
}
